const SET_IS_LOGIN = 'SET_IS_LOGIN'
const SET_API_SAFETOP = 'SET_API_SAFETOP'
const SET_API_SAFEBOT = 'SET_API_SAFEBOT'
const SET_ROUTER = 'SET_ROUTER'
const PUSH_ROUTER = 'PUSH_ROUTER'
const REMOVE_ROUTER = 'REMOVE_ROUTER'
const CLEAR_ROUTER = 'CLEAR_ROUTER'
export {
    SET_IS_LOGIN,
    SET_API_SAFETOP,
    SET_API_SAFEBOT,
    SET_ROUTER,
    PUSH_ROUTER,
    REMOVE_ROUTER,
    CLEAR_ROUTER
}